package seedu.tripbuddy.dataclass;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import org.json.JSONException;
import org.json.JSONObject;
import seedu.tripbuddy.framework.ExpenseManager;

/**
 * Stores info of a travel expense.
 */
public class Expense {
    static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
    private String name;
    private double amount;
    private String category;
    private LocalDateTime dateTime;

    public Expense(String name, double amount) {
        this.name = name;
        this.amount = amount;
        this.category = null;
        this.dateTime = LocalDateTime.now();
    }

    public Expense(String name, double amount, String category) {
        this.name = name;
        this.amount = amount;
        this.category = category;
        this.dateTime = LocalDateTime.now();
    }

    public Expense(String name, double amount, String category, String dateTimeStr) {
        this.name = name;
        this.amount = amount;
        this.category = category;
        this.dateTime = LocalDateTime.parse(dateTimeStr, FORMATTER);
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public String getCategory() {
        return category;
    }

    public String getDateTimeString() {
        return dateTime.format(FORMATTER);
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public LocalDateTime getDateTime() {
        return dateTime;
    }

    public void setDateTime(LocalDateTime dateTime) {
        this.dateTime = dateTime;
    }

    @Override
    public String toString() {
        String dateTimeStr = dateTime.format(FORMATTER);
        if (category == null) {
            return "name: " + name + ", amount: " + ExpenseManager.getFormattedAmount(amount) +
                    ", date: " + dateTimeStr;
        }
        return "name: " + name + ", amount: " + ExpenseManager.getFormattedAmount(amount)
                + ", category: " + category + ", date: " + dateTimeStr;
    }

    /**
     * Constructs a new {@link Expense} from a {@link JSONObject} generated by
     * the {@link seedu.tripbuddy.storage.FileHandler}
     */
    public static Expense fromJSON(JSONObject json) throws JSONException {
        String name = json.getString("name");
        double amount = json.getDouble("amount");
        String category = json.optString("category", null); // returns null if not present
        String dateTimeStr = json.getString("dateTime");
        return new Expense(name, amount, category, dateTimeStr);
    }
}
