@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam classIconSize 0

ExpenseManager o--> Expense : expenses

enum "<<enumeration>> \n Currency"  {
  --
  IDR
  LAK
  MYR
  PHP
  SGD
  THB
  VND
  USD
  EUR
  JPY
  GBP
  ' Attributes
  --
  - name : String
  - rate : double
  ' Methods
  --
  + convert(amount: double) : double
}

class Expense {
  {static} FORMATTER : DateTimeFormatter
  - name : String
  - amount : double
  - category : String
  - dateTime : LocalDateTime

}

class ExpenseManager {
- <u> budget : double
- <u> totalExpense: double
- <u> categories[]: String[]

+ <u>createCategory(categoryName: String): void
+ <u>addExpense(name: String, amount: double): void
+ <u>addExpense(name: String, amount: double, (categoryName: String): void
+ <u>deleteExpense(id: int): void
+ <u>deleteExpense(expenseName: String): void
+ <u>getExpensesByCategory(category: String): Expense[]
+ <u>setExpenseCategory(expenseName: String, category: String): void
+ <u>getMaxExpense(): Expense
+ <u>getMinExpense(): Expense
+ <u>getExpensesByDateRange(start: LocalDateTime, end: LocalDateTime): Expense[]
}

@enduml